### ISSUE TITLE
metadata should be able to accommodate multiple sample objects

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwas-sumstats-service#224]
We need to be able to represent multiple samples in the metadata like so:
```
samples:
  - sampleAncestry:
      - a
      - b
    sampleSize: 100
    caseControl: true
    caseCount: 100
    controlCount: 100
  - sampleAncestry:
      - b
      - c
    sampleSize: 100
    caseControl: true
    caseCount: 100
    controlCount: 100
```
1. update in sumstats service
2. update the standard repo
